# Site settings
title: Jia Fu's site
email: jiafu.low@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An awesome description here. 
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
url: "http://jiafulow.github.io" # the base hostname & protocol for your site
github_username:  jiafulow
linkedin_username: jiafulow

# Build settings
markdown: kramdown

# Gems
gems:
  - jemoji
