# Site settings
title: Jia Fu Low
author:
  name: Jia Fu Low
  email: jiafu.low@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An awesome description for an awesome site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jiafulow.github.io" # the base hostname & protocol for your site
timezone: America/Chicago
encoding: utf-8
#safe: true
#lsi: false

exclude:
  - README.md

# Social media
github_username: jiafulow
linkedin_username: jiafulow
twitter_username: jiafulow
github_repo: https://github.com/jiafulow/jiafulow.github.io

# Pagination
paginate: 5
paginate_path: "/blog/page:num"

# Blog permalink
permalink: /blog/:year/:month/:day/:title/

# Blog separator
excerpt_separator: <!--more-->

# Build settings
markdown: redcarpet
#markdown: kramdown
#highlighter: pygments

kramdown:
  input: GFM

redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "with_toc_data"]

sass:
  sass_dir: assets/stylesheets/
  #style: compressed

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
